"""This module contains all the utility functions for the project."""

__all__ = [
    "file_handler",
    "path_handler",
    "AUDIO_DIRECTORY",
    "AUDIO_DEST_DIRECTORY",
    "DATA_DIRECTORY",
    "PROJECT_DIRECTORY",
    "VIDEO_DEST_DIRECTORY",
    "VIDEO_DIRECTORY",
    "ORIGINAL_VIDEO_DIRECTORY",
    "TRANSCRIPT_DIRECTORY",
    "CAPTIONS_DIRECTORY",
    "PATH_SEPARATOR",
    "VIDEO_CAPTIONS_DIRECTORY",
    "AUDIO_TRANSLATED_SPEED_DIRECTORY",
]

from . import file_handler, path_handler
from .path_handler import (
    AUDIO_DEST_DIRECTORY,
    AUDIO_DIRECTORY,
    AUDIO_TRANSLATED_SPEED_DIRECTORY,
    CAPTIONS_DIRECTORY,
    DATA_DIRECTORY,
    ORIGINAL_VIDEO_DIRECTORY,
    PATH_SEPARATOR,
    PROJECT_DIRECTORY,
    TRANSCRIPT_DIRECTORY,
    VIDEO_CAPTIONS_DIRECTORY,
    VIDEO_DEST_DIRECTORY,
    VIDEO_DIRECTORY,
)
